version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: stegatoolkit-backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
