services:
  - type: web
    name: stegatoolkit-backend
    env: docker
    plan: free
    build:
      context: ./backend
      dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
